insert into countries(name) values ('Россия');
insert into countries(name) values ('Украина');
insert into countries(name) values ('Абхазия');
insert into countries(name) values ('Австралия');
insert into countries(name) values ('Австрия');
insert into countries(name) values ('Азербайджан');
insert into countries(name) values ('Албания');
insert into countries(name) values ('Алжир');
insert into countries(name) values ('Ангола');
insert into countries(name) values ('Ангуилья');
insert into countries(name) values ('Андорра');
insert into countries(name) values ('Антигуа и Барбуда');
insert into countries(name) values ('Антильские о-ва');
insert into countries(name) values ('Аргентина');
insert into countries(name) values ('Армения');
insert into countries(name) values ('Арулько');
insert into countries(name) values ('Афганистан');
insert into countries(name) values ('Багамские о-ва');
insert into countries(name) values ('Бангладеш');
insert into countries(name) values ('Барбадос');
insert into countries(name) values ('Бахрейн');
insert into countries(name) values ('Беларусь');
insert into countries(name) values ('Белиз');
insert into countries(name) values ('Бельгия');
insert into countries(name) values ('Бенин');
insert into countries(name) values ('Бермуды');
insert into countries(name) values ('Болгария');
insert into countries(name) values ('Боливия');
insert into countries(name) values ('Босния/Герцеговина');
insert into countries(name) values ('Ботсвана');
insert into countries(name) values ('Бразилия');
insert into countries(name) values ('Британские Виргинские о-ва');
insert into countries(name) values ('Бруней');
insert into countries(name) values ('Буркина Фасо');
insert into countries(name) values ('Бурунди');
insert into countries(name) values ('Бутан');
insert into countries(name) values ('Валлис и Футуна о-ва');
insert into countries(name) values ('Вануату');
insert into countries(name) values ('Великобритания');
insert into countries(name) values ('Венгрия');
insert into countries(name) values ('Венесуэла');
insert into countries(name) values ('Восточный Тимор');
insert into countries(name) values ('Вьетнам');
insert into countries(name) values ('Габон');
insert into countries(name) values ('Гаити');
insert into countries(name) values ('Гайана');
insert into countries(name) values ('Гамбия');
insert into countries(name) values ('Гана');
insert into countries(name) values ('Гваделупа');
insert into countries(name) values ('Гватемала');
insert into countries(name) values ('Гвинея');
insert into countries(name) values ('Гвинея-Бисау');
insert into countries(name) values ('Германия');
insert into countries(name) values ('Гернси о-в');
insert into countries(name) values ('Гибралтар');
insert into countries(name) values ('Гондурас');
insert into countries(name) values ('Гонконг');
insert into countries(name) values ('Гренада');
insert into countries(name) values ('Гренландия');
insert into countries(name) values ('Греция');
insert into countries(name) values ('Грузия');
insert into countries(name) values ('Дания');
insert into countries(name) values ('Джерси о-в');
insert into countries(name) values ('Джибути');
insert into countries(name) values ('Доминиканская республика');
insert into countries(name) values ('Египет');
insert into countries(name) values ('Замбия');
insert into countries(name) values ('Западная Сахара');
insert into countries(name) values ('Зимбабве');
insert into countries(name) values ('Израиль');
insert into countries(name) values ('Индия');
insert into countries(name) values ('Индонезия');
insert into countries(name) values ('Иордания');
insert into countries(name) values ('Ирак');
insert into countries(name) values ('Иран');
insert into countries(name) values ('Ирландия');
insert into countries(name) values ('Исландия');
insert into countries(name) values ('Испания');
insert into countries(name) values ('Италия');
insert into countries(name) values ('Йемен');
insert into countries(name) values ('Кабо-Верде');
insert into countries(name) values ('Казахстан');
insert into countries(name) values ('Камбоджа');
insert into countries(name) values ('Камерун');
insert into countries(name) values ('Канада');
insert into countries(name) values ('Катар');
insert into countries(name) values ('Кения');
insert into countries(name) values ('Кипр');
insert into countries(name) values ('Кирибати');
insert into countries(name) values ('Китай');
insert into countries(name) values ('Колумбия');
insert into countries(name) values ('Коморские о-ва');
insert into countries(name) values ('Конго (Brazzaville)');
insert into countries(name) values ('Конго (Kinshasa)');
insert into countries(name) values ('Коста-Рика');
insert into countries(name) values ('Кот-д''''Ивуар');
insert into countries(name) values ('Куба');
insert into countries(name) values ('Кувейт');
insert into countries(name) values ('Кука о-ва');
insert into countries(name) values ('Кыргызстан');
insert into countries(name) values ('Лаос');
insert into countries(name) values ('Латвия');
insert into countries(name) values ('Лесото');
insert into countries(name) values ('Либерия');
insert into countries(name) values ('Ливан');
insert into countries(name) values ('Ливия');
insert into countries(name) values ('Литва');
insert into countries(name) values ('Лихтенштейн');
insert into countries(name) values ('Люксембург');
insert into countries(name) values ('Маврикий');
insert into countries(name) values ('Мавритания');
insert into countries(name) values ('Мадагаскар');
insert into countries(name) values ('Македония');
insert into countries(name) values ('Малави');
insert into countries(name) values ('Малайзия');
insert into countries(name) values ('Мали');
insert into countries(name) values ('Мальдивские о-ва');
insert into countries(name) values ('Мальта');
insert into countries(name) values ('Мартиника о-в');
insert into countries(name) values ('Мексика');
insert into countries(name) values ('Мозамбик');
insert into countries(name) values ('Молдова');
insert into countries(name) values ('Монако');
insert into countries(name) values ('Монголия');
insert into countries(name) values ('Марокко');
insert into countries(name) values ('Мьянма (Бирма)');
insert into countries(name) values ('Мэн о-в');
insert into countries(name) values ('Намибия');
insert into countries(name) values ('Науру');
insert into countries(name) values ('Непал');
insert into countries(name) values ('Нигер');
insert into countries(name) values ('Нигерия');
insert into countries(name) values ('Нидерланды (Голландия)');
insert into countries(name) values ('Никарагуа');
insert into countries(name) values ('Новая Зеландия');
insert into countries(name) values ('Новая Каледония о-в');
insert into countries(name) values ('Норвегия');
insert into countries(name) values ('Норфолк о-в');
insert into countries(name) values ('О.А.Э.');
insert into countries(name) values ('Оман');
insert into countries(name) values ('Пакистан');
insert into countries(name) values ('Панама');
insert into countries(name) values ('Папуа Новая Гвинея');
insert into countries(name) values ('Парагвай');
insert into countries(name) values ('Перу');
insert into countries(name) values ('Питкэрн о-в');
insert into countries(name) values ('Польша');
insert into countries(name) values ('Португалия');
insert into countries(name) values ('Пуэрто Рико');
insert into countries(name) values ('Реюньон');
insert into countries(name) values ('Руанда');
insert into countries(name) values ('Румыния');
insert into countries(name) values ('США');
insert into countries(name) values ('Сальвадор');
insert into countries(name) values ('Самоа');
insert into countries(name) values ('Сан-Марино');
insert into countries(name) values ('Сан-Томе и Принсипи');
insert into countries(name) values ('Саудовская Аравия');
insert into countries(name) values ('Свазиленд');
insert into countries(name) values ('Святая Люсия');
insert into countries(name) values ('Святой Елены о-в');
insert into countries(name) values ('Северная Корея');
insert into countries(name) values ('Сейшеллы');
insert into countries(name) values ('Сен-Пьер и Микелон');
insert into countries(name) values ('Сенегал');
insert into countries(name) values ('Сент Китс и Невис');
insert into countries(name) values ('Сент-Винсент и Гренадины');
insert into countries(name) values ('Сербия');
insert into countries(name) values ('Сингапур');
insert into countries(name) values ('Сирия');
insert into countries(name) values ('Словакия');
insert into countries(name) values ('Словения');
insert into countries(name) values ('Соломоновы о-ва');
insert into countries(name) values ('Сомали');
insert into countries(name) values ('Судан');
insert into countries(name) values ('Суринам');
insert into countries(name) values ('Сьерра-Леоне');
insert into countries(name) values ('Таджикистан');
insert into countries(name) values ('Тайвань');
insert into countries(name) values ('Таиланд');
insert into countries(name) values ('Танзания');
insert into countries(name) values ('Того');
insert into countries(name) values ('Токелау о-ва');
insert into countries(name) values ('Тонга');
insert into countries(name) values ('Тринидад и Тобаго');
insert into countries(name) values ('Тувалу');
insert into countries(name) values ('Тунис');
insert into countries(name) values ('Туркменистан');
insert into countries(name) values ('Туркс и Кейкос');
insert into countries(name) values ('Турция');
insert into countries(name) values ('Уганда');
insert into countries(name) values ('Узбекистан');
insert into countries(name) values ('Уругвай');
insert into countries(name) values ('Фарерские о-ва');
insert into countries(name) values ('Фиджи');
insert into countries(name) values ('Филиппины');
insert into countries(name) values ('Финляндия');
insert into countries(name) values ('Франция');
insert into countries(name) values ('Французская Гвинея');
insert into countries(name) values ('Французская Полинезия');
insert into countries(name) values ('Хорватия');
insert into countries(name) values ('Чад');
insert into countries(name) values ('Черногория');
insert into countries(name) values ('Чехия');
insert into countries(name) values ('Чили');
insert into countries(name) values ('Швейцария');
insert into countries(name) values ('Швеция');
insert into countries(name) values ('Шри-Ланка');
insert into countries(name) values ('Эквадор');
insert into countries(name) values ('Экваториальная Гвинея');
insert into countries(name) values ('Эритрея');
insert into countries(name) values ('Эстония');
insert into countries(name) values ('Эфиопия');
insert into countries(name) values ('ЮАР');
insert into countries(name) values ('Южная Корея');
insert into countries(name) values ('Южная Осетия');
insert into countries(name) values ('Ямайка');
insert into countries(name) values ('Япония');